#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/app.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday September 9th 2024 11:24:51 am                                               #
# Modified   : Sunday November 24th 2024 05:52:32 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                      LOGGING                                                     #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s'
    file:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG # Default, possibly overridden in environment config
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: TBD # Override in environment specific configurations
      formatter: file
      interval: 1
      level: DEBUG # Default, possibly overridden in environment config
      when: midnight
  loggers:
    py4j:  # Add this block to suppress py4j logging
      level: ERROR
      handlers:
        - console
        - file
      propagate: false  # Prevent py4j logs from being propagated to the root logger
  root:
    handlers:
    - console
    - file
    level: DEBUG # Default, possibly overridden in environment config
  version: 1
# ------------------------------------------------------------------------------------------------ #
#                                         DATA                                                     #
# ------------------------------------------------------------------------------------------------ #
data:
  raw: data/raw/reviews
  frac: 1.0

# ------------------------------------------------------------------------------------------------ #
#                                     REPOSITORY                                                   #
# ------------------------------------------------------------------------------------------------ #
repository:
  dataset:
    objects:
      location: dataset/odb
    files:
      location: dataset
      partitioned: True
      centralized:
        read_kwargs:
          engine: pyarrow
        write_kwargs:
          engine: pyarrow
          compression: snappy
          index: False
          existing_data_behavior: delete_matching
          row_group_size: 1073741824
          partition_cols:
          - category
      distributed:
        write_kwargs:
          mode: error
          partitionBy:
          - category
    models:
      location: models

# ------------------------------------------------------------------------------------------------ #
#                                         SPARK                                                    #
# ------------------------------------------------------------------------------------------------ #
spark:
  memory: "96g"
  retries: 3
  parquet_block_size: 1073741824 # 1 GB Default

# ------------------------------------------------------------------------------------------------ #
#                                         DQA                                                      #
# ------------------------------------------------------------------------------------------------ #
dqa:
  dqs:
    weights:
      completeness: 0.25
      validity: 0.25
      relevance: 0.2
      uniqueness: 0.15
      privacy: 0.15
  completeness:
    weights:
      row: 0.5
      category: 0.25
      sentiment: 0.25
    columns:
      category: category
      sentiment: sa_sentiment
  validity:
    weights:
      rating: 0.2
      category: 0.1
      review: 0.6
      date: 0.1
    columns:
      rating_validity: dqd_validity_invalid_rating
      category_validity: dqd_validity_invalid_category
      date_validity: dqd_validity_invalid_review_date
      review_validity:
      - dqd_validity_contains_ctrl_chars
      - dqd_validity_contains_accents
      - dqd_validity_contains_html_chars
      - dqd_validity_contains_excess_whitespace
      - dqd_validity_contains_excess_special_chars
      - dqd_validity_contains_elongation
      - dqd_validity_contains_non_ascii_chars
      - dqd_validity_contains_excess_character_repetition
      - dqd_validity_contains_excess_sequence_repetition
      - dqd_validity_excess_word_repetition
      - dqd_validity_excess_phrase_repetition
      - dqd_validity_low_perplexity
  relevance:
    weights:
      language: 0.4
      review_length: 0.6
    columns:
      language:
      - dqd_relevance_contains_non_english_app_name
      - dqd_relevance_contains_non_english_text
      review_length: dqd_relevance_short_review
  uniqueness:
    weights:
      row: 0.3
      review_id: 0.2
      review: 0.5
    columns:
      row: dqd_uniqueness_duplicate_row
      review_id:  dqd_uniqueness_duplicate_review_id
      review: dqd_uniqueness_duplicate_review
  privacy:
    columns:
      - dqd_privacy_contains_url
      - dqd_privacy_contains_email
      - dqd_privacy_contains_phone







