#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/app.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Monday September 9th 2024 11:24:51 am                                               #
# Modified   : Tuesday November 19th 2024 03:02:40 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                      LOGGING                                                     #
# ------------------------------------------------------------------------------------------------ #
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s'
    file:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG # Default, possibly overridden in environment config
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: TBD # Override in environment specific configurations
      formatter: file
      interval: 1
      level: DEBUG # Default, possibly overridden in environment config
      when: midnight
  loggers:
    py4j:  # Add this block to suppress py4j logging
      level: ERROR
      handlers:
        - console
        - file
      propagate: false  # Prevent py4j logs from being propagated to the root logger
  root:
    handlers:
    - console
    - file
    level: DEBUG # Default, possibly overridden in environment config
  version: 1
# ------------------------------------------------------------------------------------------------ #
#                                         DATA                                                     #
# ------------------------------------------------------------------------------------------------ #
data:
  raw: data/raw/reviews
  frac: 1.0

# ------------------------------------------------------------------------------------------------ #
#                                     REPOSITORY                                                   #
# ------------------------------------------------------------------------------------------------ #
repository:
  dataset:
    objects:
      location: dataset/odb
    files:
      location: dataset
      partitioned: True
      centralized:
        read_kwargs:
          engine: pyarrow
        write_kwargs:
          engine: pyarrow
          compression: snappy
          index: False
          existing_data_behavior: delete_matching
          row_group_size: 1073741824
          partition_cols:
          - category
      distributed:
        write_kwargs:
          mode: error
          partitionBy:
          - category
    models:
      location: models

# ------------------------------------------------------------------------------------------------ #
#                                         SPARK                                                    #
# ------------------------------------------------------------------------------------------------ #
spark:
  memory: "96g"
  retries: 3
  parquet_block_size: 1073741824 # 1 GB Default

# ------------------------------------------------------------------------------------------------ #
#                                         DQA                                                      #
# ------------------------------------------------------------------------------------------------ #




