#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow.yaml                                                              #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Wednesday November 6th 2024 05:54:19 am                                             #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        stage_name: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
          - class_name: VerifyEncodingTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
              encoding_sample: 0.01
              random_state: 55
          - class_name: CastDataTypeTask
            module: discover.flow.data_prep.ingest.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
          - class_name: ReviewLengthTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
              new_column:
          - class_name: ComputeReviewAgeTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: date
              new_column: eda_review_age
          - class_name: ComputeAggDeviationStats
            module: discover.flow.data_prep.ingest.task
            params:
              agg_by: app_id
              column: rating
              new_column: eda_rating_deviation
          - class_name: ComputeAggDeviationStats
            module: discover.flow.data_prep.ingest.task
            params:
              agg_by: app_id
              column: eda_review_length
              new_column: eda_review_length_deviation
          - class_name: ComputeAggDeviationStats
            module: discover.flow.data_prep.ingest.task
            params:
              agg_by: app_id
              column: eda_review_age
              new_column: eda_review_age_deviation
          - class_name: ComputeAggDeviationStats
            module: discover.flow.data_prep.ingest.task
            params:
              agg_by: category_id
              column: rating
              new_column: eda_rating_deviation
          - class_name: ComputeAggDeviationStats
            module: discover.flow.data_prep.ingest.task
            params:
              agg_by: category_id
              column: eda_review_length
              new_column: eda_review_length_deviation
          - class_name: ComputeAggDeviationStats
            module: discover.flow.data_prep.ingest.task
            params:
              agg_by: category_id
              column: eda_review_age
              new_column: eda_review_age_deviation
      clean:
        stage_name: clean
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: clean
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: RemoveDuplicateReviewIdTask
            module: discover.flow.data_prep.clean.task
            params:
              column: id
              sort_by: date
          - class_name: URLMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[URL]'
          - class_name: EmailAddressMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[EMAIL]'
          - class_name: PhoneNumberMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[PHONE]'
          - class_name: RemoveControlCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveHTMLCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveExcessiveWhitespaceTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: " "
              column: content
          - class_name: RemoveAccentsTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
          - class_name: RemoveNonEnglishTask
            module: discover.flow.data_prep.clean.task
            params:
              column: app_name
              n_jobs: 18
          - class_name: RemoveNonEnglishTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              n_jobs: 18
          - class_name: RemoveExcessiveSpecialCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              threshold: 0.3
          - class_name: DelongationTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              threshold: 4
              max_elongation: 3
      feature:
        stage_name: feature
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: clean
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: feature
          name: review
          nlp: True
          distributed: True
        tasks:
          - class_name: NLPTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content
          - class_name: ComputePOSStatsTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content
          - class_name: ComputeBasicStatsTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content

          - class_name: ComputeTQAFiltersTask
            module: discover.flow.data_prep.feature.task
            params: {}
      tqa:
        stage_name: tqa
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: feature
          name: review
          nlp: False
          distributed: False
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: tqa
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: TQATask1
            module: discover.flow.data_prep.tqa.task
            params:
              column: content
              tqa_column: tqa_score1
              pos_count_weight: 0.4
              pos_diversity_weight: 0.2
              pos_intensity_weight: 0.1
              structural_complexity_weight: 0.2
              tqa_check_weight: 0.1
          - class_name: TQATask2Data
            module: discover.flow.data_prep.tqa.task
            params:
              filepath: data/working/dataprep/tqa_small.csv
              min_eda_review_length: 5
              max_eda_review_length: 1000
              frac: 0.01
              random_state: 202
          - class_name: TQATask2
            module: discover.flow.data_prep.tqa.task
            params:
              column: content
              tqa_column: tqa_score2
              weights_filepath: models/tqa/tqa_weights.csv
              ppl_full: 4.673929214477539
