#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow.yaml                                                              #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Tuesday November 19th 2024 01:11:55 pm                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        phase: dataprep
        stage: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: FilterTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: date
              frac: 1.0
              date: 2020
              random_state: 65
          - class_name: VerifyEncodingTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
          - class_name: CastDataTypeTask
            module: discover.flow.data_prep.ingest.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
          - class_name: AddReviewLengthTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
              new_column: review_length
      sentiment:
        phase: dataprep
        stage: sentiment
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: sentiment
          name: review
          nlp: False
          distributed: False
          cache: models/sentiment/inference/sentiments
        tasks:
          - class_name: SentimentAnalysisTask
            module: discover.flow.data_prep.sentiment.task
            params:
              column: content
              new_column: sentiment
              model_name: tabularisai/robust-sentiment-analysis

      perplexity:
        phase: dataprep
        stage: perplexity
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: sentiment
          name: review
          nlp: False
          distributed: False
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: perplexity
          name: review
          nlp: False
          distributed: False
          cache: models/perplexity/perplexity
        tasks:
          - class_name: PerplexityAnalysisTask
            module: discover.flow.data_prep.perplexity.task
            params:
              column: content
              new_column: perplexity
              model_name: distilbert/distilgpt2
              stride: 512
      dqd:
        phase: dataprep
        stage: dqd
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: perplexity
          name: review
          nlp: False
          distributed: True
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: dqd
          name: review
          nlp: False
          distributed: True
        tasks:
          - class_name: DetectOrRepairURLTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: url
              mode: detect
          - class_name: DetectOrRepairEmailAddressTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: email
              mode: detect
          - class_name: DetectOrRepairPhoneNumberTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: phone
              mode: detect
          - class_name: DetectOrRepairControlCharsTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: ctrl_chars
              mode: detect
          - class_name: DetectOrRepairAccentedCharsTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: accents
              mode: detect
          - class_name: DetectOrRepairHTMLCharsTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: html_chars
              mode: detect
          - class_name: DetectOrRepairExcessiveWhitespaceTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: excess_whitespace
              mode: detect
          - class_name: DetectOrRepairNonEnglishTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: app_name
              new_column: non_english_app_name
              mode: detect
          - class_name: DetectOrRepairNonEnglishTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: non_english_text
              mode: detect
          - class_name: DetectOrRepairExcessiveSpecialCharsTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: excess_special_chars
              threshold_char_prop: 0.3
              mode: detect
          - class_name: DetectOrRepairDuplicateReviewIdTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: id
              new_column: duplicate_review_id
              mode: detect
          - class_name: DetectOrRepairElongationTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              threshold: 4
              new_column: elongation
              mode: detect
          - class_name: DetectOrRepairNonASCIICharsTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: non_ascii_chars
              mode: detect
          - class_name: DetectOrRepairExcessNonASCIITextTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              threshold_char_prop: 0.2
              new_column: excess_non_ascii_chars
              mode: detect
          - class_name: DetectOrRepairRepeatedSequenceTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              length_of_sequence: 2
              min_repetitions: 3
              threshold: 3
              new_column: excess_sequence_repetition
              mode: detect
          - class_name: DetectOrRepairRepeatedWordsTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: excess_word_repetition
              threshold: 1
              min_repetitions: 3
              mode: detect
          - class_name: DetectOrRepairRepeatedPhrasesTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: content
              new_column: excess_phrase_repetition
              threshold: 1
              min_repetitions: 2
              mode: detect
          - class_name: DetectOrRepairLowPerplexity
            module: discover.flow.data_prep.dqd.task
            params:
              column: pa_perplexity
              new_column: low_perplexity
              threshold_percentile: 0.5
              percentile_relative_error: 0.001
              mode: detect
          - class_name: DetectOrRepairMinimumValueTask
            module: discover.flow.data_prep.dqd.task
            params:
              column: review_length
              new_column: below_min_value
              threshold: 3
              mode: detect
      tqa:
        phase: dataprep
        stage: tqa
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: dqd
          name: review
          nlp: True
          distributed: True
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: tqa
          name: review
          nlp: True
          distributed: True
        tasks:
        - class_name: NLPTask
          module: discover.flow.data_prep.tqa.task
          params:
            column: content
        - class_name: ComputeTextQualityTask
          module: discover.flow.data_prep.tqa.task
          params:
            weight_noun: 0.3
            weight_adjective: 0.3
            weight_verb: 0.2
            weight_adverb: 0.2
            weight_syntactic: 0.5
            weight_lexical: 0.5
      clean:
        stage: clean
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          distributed: True
          nlp: False
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: clean
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: URLMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[URL]'
          - class_name: EmailAddressMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[EMAIL]'
          - class_name: PhoneNumberMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[PHONE]'
          - class_name: RemoveControlCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveAccentsTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
          - class_name: RemoveHTMLCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveExcessiveWhitespaceTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: " "
              column: content
          - class_name: RemoveNonEnglishTask
            module: discover.flow.data_prep.clean.task
            params:
              column: app_name
              n_jobs: 18
          - class_name: RemoveNonEnglishTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              n_jobs: 18
          - class_name: RemoveExcessiveSpecialCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              threshold: 0.3
          - class_name: RemoveDuplicateReviewIdTask
            module: discover.flow.data_prep.clean.task
            params:
              column: id
          - class_name: DelongationTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              threshold: 4
              max_elongation: 3
          - class_name: NormalizeUnicodeTextTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
  enrichment:
    stages:
      tqa:
        phase: enrichment
        stage: tqa
        source_config:
          asset_type: dataset
          phase: enrichment
          stage: dqd
          name: review
          nlp: True
          distributed: True
        destination_config:
          asset_type: dataset
          phase: enrichment
          stage: tqa
          name: review
          nlp: True
          distributed: True
        tasks:
        - class_name: NLPTask
          module: discover.flow.data_processing.enrichment.tqa.task.py
          params:
            column: content
        - class_name: ComputeTextQualityTask
          module: discover.flow.data_prep.tqa.task
          params:
            weight_noun: 0.3
            weight_adjective: 0.3
            weight_verb: 0.2
            weight_adverb: 0.2
            weight_syntactic: 0.5
            weight_lexical: 0.5
      enrich_review:
        phase: enrichment
        stage: enrich_review
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: tqa
          name: review
          nlp: False
          distributed: True
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: edp
          name: review
          nlp: False
          distributed: True
        tasks:
          - class_name: ComputeReviewAgeTask
            module: discover.flow.data_prep.quant.task
            params:
              column: date
              new_column: nrch_review_age
          - class_name: ComputeReviewMonthTask
            module: discover.flow.data_prep.quant.task
            params:
              column: date
              new_column: nrch_review_month
          - class_name: ComputeReviewDayofWeekTask
            module: discover.flow.data_prep.quant.task
            params:
              column: date
              new_column: nrch_review_day_of_week
          - class_name: ComputeReviewHourTask
            module: discover.flow.data_prep.quant.task
            params:
              column: date
              new_column: nrch_review_hour
          - class_name: ComputePercentDeviationTask
            module: discover.flow.data_prep.quant.task
            params:
              by: category
              column: rating
              new_column: edp_pct_deviation_rating
          - class_name: ComputePercentDeviationTask
            module: discover.flow.data_prep.quant.task
            params:
              by: category
              column: review_length
              new_column: edp_pct_deviation_review_length
          - class_name: ComputePercentDeviationTask
            module: discover.flow.data_prep.quant.task
            params:
              by: category
              column: voc_sentiment
              new_column: edp_pct_deviation_sentiment
          - class_name: ComputePercentDeviationTask
            module: discover.flow.data_prep.quant.task
            params:
              by: category
              column: score
              new_column: edp_pct_deviation_score
      enrich_app:
        phase: enrichment
        stage: enrich_app
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: edp
          name: review
          nlp: False
          distributed: True
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: agg
          name: agg
          nlp: False
          distributed: True
        tasks:
          - class_name: AppAggregationTask
            module: discover.flow.data_prep.aggregation.task
            params:
              dataset_name: app
          - class_name: CategoryAggregationTask
            module: discover.flow.data_prep.aggregation.task
            params:
              dataset_name: category
