#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow.yaml                                                              #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Wednesday October 23rd 2024 12:59:20 pm                                             #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        stage_name: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: SampleTask
            module: discover.flow.data_prep.ingest.task
            params:
              frac: 1.0
              random_state: 55
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
          - class_name: VerifyEncodingTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
              encoding_sample: 0.01
              random_state: 55
          - class_name: CastDataTypeTask
            module: discover.flow.data_prep.ingest.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
          - class_name: ReviewLengthTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
      dqa:
        stage_name: dqa
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: normalize
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: dqa
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              dqa_column: dqa_duplicate_rows
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              column:
              - id
              dqa_column: dqa_duplicate_id
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              column:
              - content
              dqa_column: dqa_duplicate_review
          - class_name: DetectNullValuesTask
            module: discover.flow.data_prep.dqa.task
            params:
              dqa_column: dqa_has_null
          - class_name: DetectInvalidRatingsTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: rating
              dqa_column: dqa_invalid_rating
          - class_name: DetectNonEnglishTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_non_english_review
              n_jobs: 12
          - class_name: DetectNonEnglishTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: app_name
              dqa_column: dqa_non_english_app_name
              n_jobs: 12
          - class_name: DetectEmojiTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_has_emoji
          - class_name: DetectInvalidDatesTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: date
              dqa_column: dqa_invalid_date
              start_date: 2007
              end_date: 2024
          - class_name: DetectEmailTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_email
          - class_name: DetectURLTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_url
          - class_name: DetectPhoneNumberTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_phone_number
          - class_name: DetectSpellingErrorsTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_spelling_errors