#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow.yaml                                                              #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Thursday October 24th 2024 03:23:09 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        stage_name: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: SampleTask
            module: discover.flow.data_prep.ingest.task
            params:
              frac: 1.0
              random_state: 55
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
          - class_name: VerifyEncodingTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
              encoding_sample: 0.01
              random_state: 55
          - class_name: CastDataTypeTask
            module: discover.flow.data_prep.ingest.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
          - class_name: ReviewLengthTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
      dqa:
        defaults: &dqa_defaults
          force: False
        stage_name: dqa
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: dqa
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              column:
              dqa_column: dqa_identical_rows
              <<: *dqa_defaults
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: id
              dqa_column: dqa_identical_review_id
              <<: *dqa_defaults
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_identical_review_content
              <<: *dqa_defaults
          - class_name: DetectMissingReviewsTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: review_length
              dqa_column: dqa_review_missing
              <<: *dqa_defaults
          - class_name: DetectNonEnglishTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_non_english_review
              n_jobs: 12
              <<: *dqa_defaults
          - class_name: DetectNonEnglishTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: app_name
              dqa_column: dqa_non_english_app_name
              n_jobs: 12
              <<: *dqa_defaults
          - class_name: DetectEmojiTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_has_emoji
              <<: *dqa_defaults
          - class_name: DetectEmailTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_email
              <<: *dqa_defaults
          - class_name: DetectURLTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_url
              <<: *dqa_defaults
          - class_name: DetectPhoneNumberTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_phone_number
          - class_name: DetectNonAsciiCharsTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_non_ascii_chars
              <<: *dqa_defaults
          - class_name: DetectExcessiveNumbersTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              threshold: 7
              dqa_column: dqa_contains_excessive_numbers
              <<: *dqa_defaults
          - class_name: DetectControlCharsTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_control_chars
              <<: *dqa_defaults
          - class_name: DetectExcessiveWhitespaceTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_excessive_whitespace
              <<: *dqa_defaults
          - class_name: DetectHTMLCharsTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_HTML_chars
              <<: *dqa_defaults
          - class_name: DetectInconsistentIdNamesTask
            module: discover.flow.data_prep.dqa.task
            params:
              id_column: app_id
              name_column: app_name
              dqa_column: dqa_contains_inconsistent_app_id_name
              <<: *dqa_defaults