#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow2.yaml                                                             #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Monday October 21st 2024 12:06:11 am                                                #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        stage_name: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: FilterTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: date
              date: 2021
              frac: 1.0
              random_state: 55

        stage_name: normalize
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: normalize
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_prep.norm.task
            params:
              column: content
          - class_name: VerifyEncodingTask
            module: discover.flow.data_prep.norm.task
            params:
              column: content
              encoding_sample: 0.01
              random_state: 55
          - class_name: CastDataTypeTask
            module: discover.flow.data_prep.norm.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
      - stage_name: dqa
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: normalize
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: dqa
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: EntropyTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_entropy
              threshold: 4.75
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              dqa_column: dqa_duplicate_rows
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              column:
              - id
              dqa_column: dqa_duplicate_id
          - class_name: DetectDuplicateTask
            module: discover.flow.data_prep.dqa.task
            params:
              column:
              - content
              dqa_column: dqa_duplicate_review
          - class_name: DetectNullValuesTask
            module: discover.flow.data_prep.dqa.task
            params:
              dqa_column: dqa_has_null
          - class_name: DetectInvalidRatingsTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: rating
              dqa_column: dqa_invalid_rating
          - class_name: DetectNonEnglishTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_non_english_review
              n_jobs: 12
          - class_name: DetectNonEnglishTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: app_name
              dqa_column: dqa_non_english_app_name
              n_jobs: 12
          - class_name: DetectEmojiTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_has_emoji
          - class_name: DetectSpecialCharacterTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_excessive_special_chars
              threshold: 0.2
          - class_name: DetectInvalidDatesTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: date
              dqa_column: dqa_invalid_date
              start_date: 2007
              end_date: 2024
          - class_name: DetectProfanityTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_has_profanity
              n_jobs: 12
          - class_name: DetectEmailTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_email
          - class_name: DetectURLTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_url
          - class_name: DetectPhoneNumberTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_contains_phone_number
          - class_name: DetectSpellingErrorsTask
            module: discover.flow.data_prep.dqa.task
            params:
              column: content
              dqa_column: dqa_spelling_errors
      - stage_name: clean
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: dqa
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: clean
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: DataCleaner
            module: discover.flow.data_prep.clean.task
            params:
              dqa_column: dqa_entropy
          - class_name: DataCleaner
            module: discover.flow.data_prep.clean.task
            params:
              dqa_column: dqa_duplicate_reviee
          - class_name: DataCleaner
            module: discover.flow.data_prep.clean.task
            params:
              dqa_column: dqa_non_english_review
          - class_name: DataCleaner
            module: discover.flow.data_prep.clean.task
            params:
              dqa_column: dqa_non_english_app_name
          - class_name: DataCleaner
            module: discover.flow.data_prep.clean.task
            params:
              dqa_column: dqa_has_emoji
          - class_name: DataCleaner
            module: discover.flow.data_prep.clean.task
            params:
              dqa_column: dqa_excessive_special_chars
          - class_name: DataCleaner
            module: discover.flow.data_prep.clean.task
            params:
              dqa_column: dqa_has_profanity
          - class_name: DataCleaner
            module: discover.flow.data_prep.clean.task
            params:
              dqa_column: dqa_contains_phone_number