#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow.yaml                                                              #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Saturday November 9th 2024 02:27:16 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        stage_name: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: FilterTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: date
              frac: 1.0
              date: 2008
      clean:
        stage_name: clean
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: clean
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: CastDataTypeTask
            module: discover.flow.data_prep.clean.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
          - class_name: URLMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[URL]'
          - class_name: EmailAddressMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[EMAIL]'
          - class_name: PhoneNumberMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[PHONE]'
          - class_name: RemoveControlCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveAccentsTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
          - class_name: RemoveHTMLCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveExcessiveWhitespaceTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: " "
              column: content
          - class_name: RemoveNonEnglishTask
            module: discover.flow.data_prep.clean.task
            params:
              column: app_name
              n_jobs: 18
          - class_name: RemoveNonEnglishTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              n_jobs: 18
          - class_name: RemoveExcessiveSpecialCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              threshold: 0.3
          - class_name: RemoveDuplicateReviewIdTask
            module: discover.flow.data_prep.clean.task
            params:
              column: id
              sort_by: date
          - class_name: DelongationTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              threshold: 4
              max_elongation: 3
          - class_name: NormalizeUnicodeTextTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
          - class_name: VerifyEncodingTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
          - class_name: RemoveNonASCIICharsTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
  enrichment:
      stages:
        metadata:
          stage_name: metadata
          source_config:
            asset_type: dataset
            phase: dataprep
            stage: clean
            name: review
            nlp: False
            distributed: True
          destination_config:
            asset_type: dataset
            phase: enrichment
            stage: metadata
            name: review
            nlp: False
            distributed: True
          tasks:
            - class_name: ComputeReviewAgeTask
              module: discover.flow.enrich.metadata.task
              params:
                column: date
                new_column: enrichment_meta_review_age
            - class_name: ComputeReviewLengthTask
              module: discover.flow.enrich.metadata.task
              params:
                column: content
                new_column: enrichment_meta_review_length
            - class_name: ComputeReviewMonthTask
              module: discover.flow.enrich.metadata.task
              params:
                column: date
                new_column: enrichment_meta_review_month
            - class_name: ComputeReviewDayofWeekTask
              module: discover.flow.enrich.metadata.task
              params:
                column: date
                new_column: enrichment_meta_review_day_of_week
            - class_name: ComputeReviewHourTask
              module: discover.flow.enrich.metadata.task
              params:
                column: date
                new_column: enrichment_meta_review_hour
        sentiment:
          stage_name: sentiment
          source_config:
            asset_type: dataset
            phase: enrichment
            stage: metadata
            name: review
            nlp: False
            distributed: False
          destination_config:
            asset_type: dataset
            phase: enrichment
            stage: sentiment
            name: review
            nlp: False
            distributed: False
          tasks:
            - class_name: SpacySentimentAnalysisTask
              module: discover.flow.enrich.sentiment.task
              params:
                column: content
                new_column: enrichment_sentiment
                pipeline: en_core_web_sm
            - class_name: SentimentClassificationTask
              module: discover.flow.enrich.sentiment.task
              params:
                column: enrichment_sentiment
                new_column: enrichment_sentiment_classification
                min_sentiment: -1.0
                max_sentiment: 1.0
        quality:
          stage_name: quality
          source_config:
            asset_type: dataset
            phase: enrichment
            stage: sentiment
            name: review
            nlp: True
            distributed: True
          destination_config:
            asset_type: dataset
            phase: enrichment
            stage: quality
            name: review
            nlp: True
            distributed: True
          tasks:
            - class_name: NLPTask
              module: discover.flow.enrich.quality.task
              params:
                column: content
            - class_name: ComputePOSStatsTask
              module: discover.flow.enrich.quality.task
              params:
                column: content
            - class_name: ComputeBasicStatsTask
              module: discover.flow.enrich.quality.task
              params:
                column: content
            - class_name: ComputeTQAFiltersTask
              module: discover.flow.enrich.quality.task
              params: {}
            - class_name: TQATask1
              module: discover.flow.enrich.quality.task
              params:
                column: content
                new_column: enrichment_tqa_score1
                pos_count_weight: 0.4
                pos_diversity_weight: 0.2
                pos_intensity_weight: 0.1
                structural_complexity_weight: 0.2
                tqa_check_weight: 0.1
            - class_name: TQATask2
              module: discover.flow.enrich.quality.task
              params:
                column: content
                new_column: enrichment_tqa_score2
                ppl_filepath: models/tqa/tqa_ppl.csv
                ppl_full: 4.673929214477539
            - class_name: TQATask3
              module: discover.flow.enrich.quality.task
              params:
                tqa1_weight: 0.4
                tqa2_weight: 0.6
                new_column: enrichment_tqa_score_final
        deviation:
          stage_name: deviation
          source_config:
            asset_type: dataset
            phase: enrichment
            stage: quality
            name: review
            nlp: False
            distributed: True
          destination_config:
            asset_type: dataset
            phase: enrichment
            stage: deviation
            name: review
            nlp: False
            distributed: True
          tasks:
            - class_name: ComputePercentDeviationTask
              module: discover.flow.enrich.deviation.task
              params:
                by: category
                column: rating
                new_column: enrichment_pct_deviation_rating
            - class_name: ComputePercentDeviationTask
              module: discover.flow.enrich.deviation.task
              params:
                by: category
                column: enrichment_meta_review_length
                new_column: enrichment_pct_deviation_review_length
            - class_name: ComputePercentDeviationTask
              module: discover.flow.enrich.deviation.task
              params:
                by: category
                column: enrichment_sentiment
                new_column: enrichment_pct_deviation_sentiment
            - class_name: ComputePercentDeviationTask
              module: discover.flow.enrich.deviation.task
              params:
                by: category
                column: enrichment_tqa_score_final
                new_column: enrichment_pct_deviation_tqa_score_final
  aggregation:
      stages:
        app:
          stage_name: app
          source_config:
            asset_type: dataset
            phase: enrichment
            stage: deviation
            name: review
            nlp: False
            distributed: True
          destination_config:
            asset_type: dataset
            phase: aggregation
            stage: app
            name: app
            nlp: False
            distributed: True
          tasks:
            - class_name: AppAggregationTask
              module: discover.flow.aggregation.task
              params: {}
        category:
          stage_name: category
          source_config:
            asset_type: dataset
            phase: enrichment
            stage: deviation
            name: review
            nlp: False
            distributed: True
          destination_config:
            asset_type: dataset
            phase: aggregation
            stage: category
            name: category
            nlp: False
            distributed: True
          tasks:
            - class_name: CategoryAggregationTask
              module: discover.flow.aggregation.task
              params: {}