#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow.yaml                                                              #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Saturday October 26th 2024 02:42:31 pm                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        stage_name: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: SampleTask
            module: discover.flow.data_prep.ingest.task
            params:
              frac: 1.0
              random_state: 55
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
          - class_name: VerifyEncodingTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
              encoding_sample: 0.01
              random_state: 55
          - class_name: CastDataTypeTask
            module: discover.flow.data_prep.ingest.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
          - class_name: ReviewLengthTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
      clean:
        stage_name: clean
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: clean
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: RemoveDuplicateReviewIdTask
            module: discover.flow.data_prep.clean.task
            params:
              column: id
              sort_by: date
          - class_name: URLMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[URL]'
          - class_name: EmailAddressMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[EMAIL]'
          - class_name: PhoneNumberMaskTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              replacement: '[PHONE]'
          - class_name: RemoveSpecialCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveControlCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveHTMLCharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveExcessiveWhitespaceTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: " "
              column: content
          - class_name: RemoveNonASCIICharsTask
            module: discover.flow.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveAccentsTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
          - class_name: DetectNonEnglishTask
            module: discover.flow.data_prep.clean.task
            params:
              column: app_name
              dc_column: dc_non_english_app_name
              n_jobs: 18
          - class_name: DetectNonEnglishTask
            module: discover.flow.data_prep.clean.task
            params:
              column: content
              dc_column: dc_non_english_review
              n_jobs: 18
      feature:
        stage_name: feature
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: clean
          name: review
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: feature
          name: review
          nlp: True
          distributed: True
        tasks:
          - class_name: NLPTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content
          - class_name: ComputeSentenceStatsTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content
          - class_name: ComputePOSStatsTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content
          - class_name: ComputeBasicStatsTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content
          - class_name: ComputeReviewAgeTask
            module: discover.flow.data_prep.feature.task
            params:
              column: date
              stats_column: stats_review_age
          - class_name: ComputeAggDeviationStats
            module: discover.flow.data_prep.feature.task
            params:
              agg_by: app_id
              column: rating
              stats_column: stats_rating_deviation
          - class_name: ComputeAggDeviationStats
            module: discover.flow.data_prep.feature.task
            params:
              agg_by: app_id
              column: review_length
              stats_column: stats_review_length_deviation
          - class_name: ComputeEntropyTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content
              stats_column: info_entropy
          - class_name: ComputeTQAStatsTask
            module: discover.flow.data_prep.feature.task
            params: {}
          - class_name: ComputeReadabilityTask
            module: discover.flow.data_prep.feature.task
            params:
              column: content
              stats_column: readability_flesch_reading_ease