#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow.yaml                                                              #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Sunday November 17th 2024 12:01:46 am                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        phase: dataprep
        stage: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: FilterTask
            module: discover.flow.data_processing.data_prep.ingest.task
            params:
              column: date
              frac: 1.0
              date: 2020
              random_state: 65
          - class_name: VerifyEncodingTask
            module: discover.flow.data_processing.data_prep.ingest.task
            params:
              column: content
          - class_name: CastDataTypeTask
            module: discover.flow.data_processing.data_prep.ingest.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
          - class_name: AddReviewLengthTask
            module: discover.flow.data_processing.data_prep.ingest.task
            params:
              column: content
              new_column: review_length
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_processing.data_prep.ingest.task
            params:
              column: content
      tqd:
        phase: dataprep
        stage: tqd
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: perplexity
          name: review
          nlp: True
          distributed: True
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: tqd
          name: review
          nlp: True
          distributed: True
        tasks:
          - class_name: DetectOrRepairURLTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: url
              mode: detect
          - class_name: DetectOrRepairEmailAddressTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: email
              mode: detect
          - class_name: DetectOrRepairPhoneNumberTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: phone
              mode: detect
          - class_name: DetectOrRepairControlCharsTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: ctrl_chars
              mode: detect
          - class_name: DetectOrRepairAccentedCharsTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: accents
              mode: detect
          - class_name: DetectOrRepairHTMLCharsTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: html_chars
              mode: detect
          - class_name: DetectOrRepairExcessiveWhitespaceTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: excess_whitespace
              mode: detect
          - class_name: DetectOrRepairNonEnglishTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: app_name
              new_column: non_english_app_name
              mode: detect
          - class_name: DetectOrRepairNonEnglishTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: non_english_text
              mode: detect
          - class_name: DetectOrRepairExcessiveSpecialCharsTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: excess_special_chars
              threshold_char_prop: 0.3
              mode: detect
          - class_name: DetectOrRepairDuplicateReviewIdTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: id
              new_column: duplicate_review_id
              mode: detect
          - class_name: DetectOrRepairElongationTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              threshold: 4
              new_column: elongation
              mode: detect
          - class_name: DetectOrRepairNonASCIICharsTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: non_ascii_chars
              mode: detect
          - class_name: DetectOrRepairNonASCIITextTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              threshold_char_prop: 0.2
              new_column: excess_non_ascii_chars
              mode: detect
          - class_name: DetectOrRepairRepeatedSequenceTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              length_of_sequence: 2
              min_repetitions: 3
              threshold: 3
              new_column: excess_sequence_repetition
              mode: detect
          - class_name: DetectOrRepairRepeatedWordsTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: excess_word_repetition
              threshold: 1
              min_repetitions: 3
              mode: detect
          - class_name: DetectOrRepairRepeatedPhrasesTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: content
              new_column: excess_phrase_repetition
              threshold: 1
              min_repetitions: 2
              mode: detect
          - class_name: DetectOrRepairOutliersTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: review_length
              iqr_threshold: 3
              mode: detect
              new_column: review_length_outlier
          - class_name: DetectOrRepairOutliersTask
            module: discover.flow.data_processing.data_prep.tqd.task
            params:
              column: an_perplexity
              iqr_threshold: 3
              mode: detect
              new_column: perplexity_outlier
      tqa:
        phase: dataprep
        stage: tqa
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: tqd
          name: review
          nlp: True
          distributed: True
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: tqa
          name: review
          nlp: True
          distributed: True
        tasks:
        - class_name: NLPTask
          module: discover.flow.data_processing.data_prep.tqa.task
          params:
            column: content
        - class_name: ComputeSyntacticStatsTask
          module: discover.flow.data_processing.data_prep.tqa.task
          params:
            column: content
        - class_name: ComputeLexicalStatsTask
          module: discover.flow.data_processing.data_prep.tqa.task
          params:
            column: content
        - class_name: ComputeSyntacticLexicalScoresTask
          module: discover.flow.data_processing.data_prep.tqa.task
          params:
            column: content
            new_column: syntactic_lexical_score
            pos_diversity_weight: 0.3
            pos_density_weight: 0.3
            lexical_complexity_weight: 0.4
        - class_name: ComputePerplexityFiltersTask
          module: discover.flow.data_processing.data_prep.tqa.task
          params: {}
        - class_name: ComputePerplexityWeights
          module: discover.flow.data_processing.data_prep.tqa.task
          params:
            pp_filepath: models/tqa/pp_weights.csv
            column: an_perplexity
            pp_filter_prefix: tqf_
        - class_name: ComputeCoherenceScoreTask
          module: discover.flow.data_processing.data_prep.tqa.task
          params:
            new_column: coherence_score
            pp_filepath: models/tqa/pp_weights.csv
        - class_name: ComputeTextQualityScore
          module: discover.flow.data_processing.data_prep.tqa.task
          params:
            syntactic_weight: 0.4
            perplexity_weight: 0.6
            new_column: score
      clean:
        stage: clean
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          distributed: True
          nlp: False
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: clean
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: URLMaskTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: content
              replacement: '[URL]'
          - class_name: EmailAddressMaskTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: content
              replacement: '[EMAIL]'
          - class_name: PhoneNumberMaskTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: content
              replacement: '[PHONE]'
          - class_name: RemoveControlCharsTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveAccentsTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: content
          - class_name: RemoveHTMLCharsTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              replacement: ""
              column: content
          - class_name: RemoveExcessiveWhitespaceTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              replacement: " "
              column: content
          - class_name: RemoveNonEnglishTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: app_name
              n_jobs: 18
          - class_name: RemoveNonEnglishTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: content
              n_jobs: 18
          - class_name: RemoveExcessiveSpecialCharsTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: content
              threshold: 0.3
          - class_name: RemoveDuplicateReviewIdTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: id
          - class_name: DelongationTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: content
              threshold: 4
              max_elongation: 3
          - class_name: NormalizeUnicodeTextTask
            module: discover.flow.data_processing.data_prep.clean.task
            params:
              column: content
  enrichment:
    stages:
      enrich_review:
        phase: enrichment
        stage: enrich_review
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: tqa
          name: review
          nlp: False
          distributed: True
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: edp
          name: review
          nlp: False
          distributed: True
        tasks:
          - class_name: ComputeReviewAgeTask
            module: discover.flow.data_processing.data_prep.quant.task
            params:
              column: date
              new_column: nrch_review_age
          - class_name: ComputeReviewMonthTask
            module: discover.flow.data_processing.data_prep.quant.task
            params:
              column: date
              new_column: nrch_review_month
          - class_name: ComputeReviewDayofWeekTask
            module: discover.flow.data_processing.data_prep.quant.task
            params:
              column: date
              new_column: nrch_review_day_of_week
          - class_name: ComputeReviewHourTask
            module: discover.flow.data_processing.data_prep.quant.task
            params:
              column: date
              new_column: nrch_review_hour
          - class_name: ComputePercentDeviationTask
            module: discover.flow.data_processing.data_prep.quant.task
            params:
              by: category
              column: rating
              new_column: edp_pct_deviation_rating
          - class_name: ComputePercentDeviationTask
            module: discover.flow.data_processing.data_prep.quant.task
            params:
              by: category
              column: review_length
              new_column: edp_pct_deviation_review_length
          - class_name: ComputePercentDeviationTask
            module: discover.flow.data_processing.data_prep.quant.task
            params:
              by: category
              column: an_sentiment
              new_column: edp_pct_deviation_sentiment
          - class_name: ComputePercentDeviationTask
            module: discover.flow.data_processing.data_prep.quant.task
            params:
              by: category
              column: score
              new_column: edp_pct_deviation_score
      enrich_app:
        phase: enrichment
        stage: enrich_app
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: edp
          name: review
          nlp: False
          distributed: True
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: agg
          name: agg
          nlp: False
          distributed: True
        tasks:
          - class_name: AppAggregationTask
            module: discover.flow.data_processing.data_prep.aggregation.task
            params:
              dataset_name: app
          - class_name: CategoryAggregationTask
            module: discover.flow.data_processing.data_prep.aggregation.task
            params:
              dataset_name: category
