#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/base/flow.yaml                                                              #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Monday October 21st 2024 01:11:44 am                                                #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
phases:
  dataprep:
    stages:
      ingest:
        stage_name: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: FilterTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: date
              date: 2021
              frac: 1.0
              random_state: 55
          - class_name: RemoveNewlinesTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
          - class_name: VerifyEncodingTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
              encoding_sample: 0.01
              random_state: 55
          - class_name: CastDataTypeTask
            module: discover.flow.data_prep.ingest.task
            params:
              datatypes:
                id: string
                app_id: string
                app_name: string
                category_id: category
                category: category
                author: string
                rating: int16
                content: string
                vote_count: int64
                vote_sum: int64
                date: datetime64[ms]
          - class_name: ReviewLengthTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: content
