#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config/prod/app.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Thursday January 23rd 2025 01:19:19 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
env: prod
# ------------------------------------------------------------------------------------------------ #
#                                        LOGGING                                                   #
# ------------------------------------------------------------------------------------------------ #
logging:
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: INFO # Default, possibly overridden in environment config
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/prod/log # Override in environment specific configurations
      formatter: file
      interval: 1
      level: INFO # Default, possibly overridden in environment config
      when: midnight
  loggers:
    py4j:  # Add this block to suppress py4j logging
      level: ERROR
      handlers:
        - console
        - file
      propagate: false  # Prevent py4j logs from being propagated to the root logger
  root:
    handlers:
    - console
    - file
    level: INFO # Default, possibly overridden in environment config
  version: 1

# ------------------------------------------------------------------------------------------------ #
#                                    OPERATIONS                                                    #
# ------------------------------------------------------------------------------------------------ #
ops:
  basedir: ops/prod  # Base directory for operations data.
  cache: ops/prod/cache
# ------------------------------------------------------------------------------------------------ #
#                                    REPOSITORY                                                    #
# ------------------------------------------------------------------------------------------------ #
repository:
  dataset:
    fal: workspace/prod/datasets/fal/
    dal: workspace/prod/datasets/dal/
    ral: workspace/prod/datasets/ral/