#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config/app/prod.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Thursday October 17th 2024 12:46:43 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
env: prod
# ------------------------------------------------------------------------------------------------ #
#                                      LOGGING                                                     #
# ------------------------------------------------------------------------------------------------ #
logging:
  handlers:
    file:
      filename: logs/prod/log


# ------------------------------------------------------------------------------------------------ #
#                                   WORKSPACE                                                      #
# ------------------------------------------------------------------------------------------------ #
workspace: workspace/prod