#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config/prod/app.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Tuesday January 21st 2025 10:58:10 pm                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
env: prod
# ------------------------------------------------------------------------------------------------ #
#                                       WORKSPACE                                                  #
# ------------------------------------------------------------------------------------------------ #
workspace:
  id: prod
  name: Production Workspace
  location: workspace/prod
  assets:
    datasets:
      files: workspace/prod/datasets/files/
      metadata: workspace/prod/datasets/metadata
      registry: workspace/prod/datasets/registry
    models: workspace/prod/models/
  ops:
    version: workspace/prod/ops/version/version
    tempdir: workspace/prod/ops/tempdir/
    flowstate: workspace/prod/ops/flow/flowstate
# ------------------------------------------------------------------------------------------------ #
#                                        LOGGING                                                   #
# ------------------------------------------------------------------------------------------------ #
logging:
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: INFO # Default, possibly overridden in environment config
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/prod/log # Override in environment specific configurations
      formatter: file
      interval: 1
      level: INFO # Default, possibly overridden in environment config
      when: midnight
  loggers:
    py4j:  # Add this block to suppress py4j logging
      level: ERROR
      handlers:
        - console
        - file
      propagate: false  # Prevent py4j logs from being propagated to the root logger
  root:
    handlers:
    - console
    - file
    level: INFO # Default, possibly overridden in environment config
  version: 1

# ------------------------------------------------------------------------------------------------ #
#                                    OPERATIONS                                                    #
# ------------------------------------------------------------------------------------------------ #
ops:
  basedir: ops/prod  # Base directory for operations data.
  cache: ops/prod/cache