#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config/dev.yaml                                                                    #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Tuesday September 17th 2024 07:16:11 pm                                             #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
env: dev
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(message)s'
    file:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/dev.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
    - console
    - file
    level: INFO
  version: 1

# ------------------------------------------------------------------------------------------------ #
database:
  sqlite:
    url: sqlite:///ops/dev/db/sqlite.db
    filepath: ops/dev/db/sqlite.db
    pool_size: 5 # Default for non-concurrent applications
    max_overflow: 10 # Allow temporary connections beyond pool_size if needed
# ------------------------------------------------------------------------------------------------ #
dataset:
  frac: 0.01 # What proportion of the overall dataset to sample for this environment
  random_state: 22
  basedir: data
  format: parquet
  file_ext: ""
  save_kwargs:
    partition_cols: ["category"]
    row_group_size: 10485760  # 10Mb
    existing_data_behavior: delete_matching
# ------------------------------------------------------------------------------------------------ #
ops:
  basedir: ops/dev  # Base directory for operations data.
  cache:
    basedir: ops/dev/cache # Base directory for cache
    ttl: 90 # In days
    refresh_on_access: True  # Access resets the expiration clock.
# ------------------------------------------------------------------------------------------------ #
workspace: workspace/dev