#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config/test.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Monday September 23rd 2024 02:57:23 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
env: test
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s'
    file:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/test.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
    - console
    - file
    level: DEBUG
  version: 1

# ------------------------------------------------------------------------------------------------ #
database:
  sqlite:
    url: sqlite:///ops/test/db/sqlite.db
    filepath: ops/test/db/sqlite.db
    pool_size: 5 # Default for non-concurrent applications
    max_overflow: 10 # Allow temporary connections beyond pool_size if needed

# ------------------------------------------------------------------------------------------------ #
dataset:
  pandas:
    engine: pyarrow
    compression: snappy
    index: False
    partition_cols: [category]
    row_group_size: 1073741824   # 1Gb
    existing_data_behavior: delete_matching
  spark:
    mode: error
    partition_cols: [category]

# ------------------------------------------------------------------------------------------------ #
ops:
  basedir: ops/test  # Base directory for operations data.
  idgen: ops/test/idgen # Shelve key value store for id generation.
  cache:
    registry: ops/test/cache/registry
    data: ops/test/cache/data
    archive: ops/test/cache/archive
    ttl: 0 # In days
    refresh_on_access: True  # Access resets the expiration clock.
# ------------------------------------------------------------------------------------------------ #
aws:
  bucket: appvoc
  s3_key: test/reviews.tar.gz

# ------------------------------------------------------------------------------------------------ #
workspace: workspace/test  # Base directory for environment workspace