#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config/test.yaml                                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Friday September 13th 2024 11:41:56 pm                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
env: test
logging:
  disable_existing_loggers: false
  formatters:
    console:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(funcName)s] : %(message)s'
    file:
      datefmt: '%m/%d/%Y %I:%M:%S %p'
      format: '[%(asctime)s] [%(levelname)s] [%(name)s] [%(module)s] [%(funcName)s]
        : %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: DEBUG
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/test.log
      formatter: file
      interval: 1
      level: DEBUG
      when: midnight
  root:
    handlers:
    - console
    - file
    level: DEBUG
  version: 1

# ------------------------------------------------------------------------------------------------ #
database:
  sqlite:
    url: sqlite:///workspace/test/db/sqlite.db
    filepath: workspace/test/db/sqlite.db
    pool_size: 5 # Default for non-concurrent applications
    max_overflow: 10 # Allow temporary connections beyond pool_size if needed

# ------------------------------------------------------------------------------------------------ #
dataset:
  basedir: data
  frac: 0.1 # What proportion of the overall dataset to sample for this environment
  random_state: 22
  format: parquet
  file_ext: ""
  save_kwargs:
    partition_cols: ["category"]
    row_group_size: 1048576  # 1Mb
    existing_data_behavior: delete_matching
# ------------------------------------------------------------------------------------------------ #
ops:
  cache: ops/test/cache/cachenow
  idxgen:
    runid: ops/test/identity/runid

aws:
  bucket: appvoc
  s3_key: test/reviews.tar.gz