#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config/app/test.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Saturday October 12th 2024 09:06:29 am                                              #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
env: test
# ------------------------------------------------------------------------------------------------ #
#                                      LOGGING                                                     #
# ------------------------------------------------------------------------------------------------ #
logging:
  handlers:
    file:
      filename: logs/test/log
# ------------------------------------------------------------------------------------------------ #
#                                    REPOSITORY                                                    #
# ------------------------------------------------------------------------------------------------ #
repository:
  dataset:
    fao:
      centralized:
        write_kwargs:
          row_group_size: 536870912 # 512 MB



# ------------------------------------------------------------------------------------------------ #
#                                      SPARK                                                       #
# ------------------------------------------------------------------------------------------------ #
spark:
  parquet_block_size: 536870912 # 512 MB

# ------------------------------------------------------------------------------------------------ #
#                                   WORKSPACE                                                      #
# ------------------------------------------------------------------------------------------------ #
workspace: workspace/test