#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.12                                                                             #
# Filename   : /config/dev/app.yaml                                                                #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Thursday April 20th 2023 01:19:19 pm                                                #
# Modified   : Monday December 30th 2024 04:45:20 am                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2023 John James                                                                 #
# ================================================================================================ #
env: dev
# ------------------------------------------------------------------------------------------------ #
#                                           SETUP                                                  #
# ------------------------------------------------------------------------------------------------ #
setup:
  dataset:
    filepath: data/stage/dev/reviews

# ------------------------------------------------------------------------------------------------ #
#                                   WORKSPACE                                                      #
# ------------------------------------------------------------------------------------------------ #
workspace:
  id: dev
  name: Development Workspace
  location: workspace/dev
  metadata:
    dataset: workspace/dev/metadata/datasets/datasets
    model: workspace/dev/metadata/models/models
    experiment: workspace/dev/metadata/experiments/experiments
  files: workspace/dev/files/
  ops:
    version: workspace/dev/ops/version/version
    tempdir: workspace/dev/ops/tempdir/

# ------------------------------------------------------------------------------------------------ #
#                                      LOGGING                                                     #
# ------------------------------------------------------------------------------------------------ #
logging:
  handlers:
    console:
      class: logging.StreamHandler
      formatter: console
      level: INFO # Default, possibly overridden in environment config
      stream: ext://sys.stderr
    file:
      backupCount: 0
      class: logging.handlers.TimedRotatingFileHandler
      filename: logs/dev/log # Override in environment specific configurations
      formatter: file
      interval: 1
      level: INFO # Default, possibly overridden in environment config
      when: midnight
  loggers:
    py4j:  # Add this block to suppress py4j logging
      level: ERROR
      handlers:
        - console
        - file
      propagate: false  # Prevent py4j logs from being propagated to the root logger
  root:
    handlers:
    - console
    - file
    level: INFO # Default, possibly overridden in environment config
  version: 1

# ------------------------------------------------------------------------------------------------ #
#                                    REPOSITORY                                                    #
# ------------------------------------------------------------------------------------------------ #
repository:
  dataset:
    fao:
      centralized:
        write_kwargs:
          row_group_size: 1073741824 # 1 GB



# ------------------------------------------------------------------------------------------------ #
#                                      SPARK                                                       #
# ------------------------------------------------------------------------------------------------ #
spark:
  parquet_block_size: 536870912 # 512 MB



# ------------------------------------------------------------------------------------------------ #
#                                    OPERATIONS                                                    #
# ------------------------------------------------------------------------------------------------ #
ops:
  basedir: ops/dev  # Base directory for operations data.
  cache: ops/dev/cache