#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/dev/flow.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Wednesday November 13th 2024 12:15:34 am                                            #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                        PHASES                                                    #
# ------------------------------------------------------------------------------------------------ #
phases:
  dataprep:
    stages:
      ingest:
        stage_name: ingest
        source_config:
          filepath: data/raw/reviews
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          nlp: False
          distributed: False
        tasks:
          - class_name: FilterTask
            module: discover.flow.data_prep.ingest.task
            params:
              column: date
              frac: 0.01
              date: 2020
              random_state: 51