#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppVoCAI-Discover                                                                   #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.14                                                                             #
# Filename   : /config/dev/flow.yaml                                                               #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appvocai-discover                               #
# ------------------------------------------------------------------------------------------------ #
# Created    : Saturday October 12th 2024 05:28:09 am                                              #
# Modified   : Sunday December 15th 2024 06:47:39 am                                               #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
#                                        PHASES                                                    #
# ------------------------------------------------------------------------------------------------ #
phases:
  dataprep:
    stages:
      ingest:
        source_config:
          filepath: data/stage/dev/reviews
      perplexity:
        phase: dataprep
        stage: perplexity
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: ingest
          name: review
          dataframe_type_id: pandas
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: perplexity
          name: review
          dataframe_type_id: pandas
        tasks:
          - class_name: PerplexityAnalysisTask
            module: discover.flow.task.model.perplexity
            params:
              column: content
              new_column: perplexity
              model_name: distilbert/distilgpt2
              stride: 512
              cache_filepath: models/perplexity/perplexity_dev.csv
              device_local: False
      sentiment:
        phase: dataprep
        stage: sentiment
        source_config:
          asset_type: dataset
          phase: dataprep
          stage: perplexity
          name: review
          dataframe_type_id: pandas
        destination_config:
          asset_type: dataset
          phase: dataprep
          stage: sentiment
          name: review
          dataframe_type_id: pandas
        tasks:
          - class_name: SentimentAnalysisTask
            module: discover.flow.task.model.sentiment
            params:
              column: content
              new_column: sentiment
              model_name: tabularisai/robust-sentiment-analysis
              cache_filepath: models/sentiment/inference/sentiments_dev.csv
              device_local: False
