#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : AppInsight                                                                          #
# Version    : 0.1.0                                                                               #
# Python     : 3.12.3                                                                              #
# Filename   : /config/application/database.yaml                                                   #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john@variancexplained.com                                                           #
# URL        : https://github.com/variancexplained/appinsight                                      #
# ------------------------------------------------------------------------------------------------ #
# Created    : Wednesday July 3rd 2024 09:50:52 am                                                 #
# Modified   : Wednesday July 3rd 2024 09:51:06 am                                                 #
# ------------------------------------------------------------------------------------------------ #
# License    : MIT License                                                                         #
# Copyright  : (c) 2024 John James                                                                 #
# ================================================================================================ #
# ------------------------------------------------------------------------------------------------ #
setup:
  database:
    profile:
      exists: scripts/sqlite3/profile/exists.sql
      drop: scripts/sqlite3/profile/drop.sql
      create: scripts/sqlite3/profile/create.sql
    backup:
      exists: scripts/sqlite3/backup/exists.sql
      drop: scripts/sqlite3/backup/drop.sql
      create: scripts/sqlite3/backup/create.sql    
    dataset:
      exists: scripts/sqlite3/dataset/exists.sql
      drop: scripts/sqlite3/dataset/drop.sql
      create: scripts/sqlite3/dataset/create.sql    